### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Pewww** [Pewww/pr-tree-viewer#1]
- [ ] 다크모드 대응 (Optional)
- [x] 익스텐션 엘리먼트 숨김 처리 가능하도록 (페이지 내에서 완전 제거)
- [x] 로고 설정 및 실제 배포
- [x] 스크롤이 범위를 벗어나도 사라지지 않도록 위치 Fix
- [ ] Show, Hide를 재빠르게 번갈아가며 누를 시 생기는 버그 해결
- [x] README와 크롬 스토어에 변경된 디자인 올리기
- [x] 1.0.2 버전 스타일 및 기타 이슈 해결 - (Hotfix, Rollback and upgrade to 1.0.21)
- [ ] 헤더 쪽은 같이 스크롤 되지 않도록 고정 (1.1.3에 반영할 것)

**Comment by Pewww** [comment]
필요한 것들은 따로 이슈 파서 작업하장
